name: CI
on: [push, pull_request]

jobs:
  witx-valid:
    name: Check WITX files are valid
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate bindings from WITX
      run: scripts/check-witx
